# ##################################
# Base Config
# ##################################



# audit schema details
auditdb: metadata
audituser: proc_mon/checkwork@metastore.cpogzsn5ewwn.ap-southeast-2.rds.amazonaws.com:3306/metadata


